name: deploy Nodejs Application 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name:  Deploy Via SSH
          uses: appleboy/ssh-action@master
          with:
            host: 13.200.233.70
            username: root
            key: ${{ secrets.SSH_KEY }}
            script: |
             cd /root/nodejs-application-demo
             git pull 
             
            